version: '3.4'

services:
  productcatalog.webapi:
    image:  ${DOCKER_REGISTRY}productcatalogwebapi
    build:
      context: .
      dockerfile: src/ProductCatalog.WebAPI/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "abc,12345678"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433